server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/v1/customers/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/v1/accounts/**
        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction-service/v1/transactions/**
        - id: AUTH-SERVICE
          uri: http://localhost:8880
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/realms/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8880/realms/e-bank-dev/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8880/realms/e-bank-dev
        registration:
          keycloak:
            provider: keycloak
            client-id: e-bank-api
            #client-secret: UBT5DfCyOiGB9PQKa6fM2wzePTjRC8kI
            #authorization-grant-type: authorization_code
            scope: openid

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    client:
      server-url:
        default-zone: http://localhost:8761/eureka/
